# -*- coding: utf-8 -*-
"""NL HW4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biiFZp0c1fdX7dsTsKpkmoj5dnLbFNUn
"""

#Question 1
#Toy data set
text = "hello hello help hello help hello"

#pytoch model
import torch
import torch.nn as nn
import torch.optim as optim

# ---- Hyperparameters ----
vocab = list(set(text))
vocab_size = len(vocab)
char2idx = {c:i for i,c in enumerate(vocab)}
idx2char = {i:c for c,i in char2idx.items()}

seq_len = 5
hidden_size = 128
lr = 0.01
epochs = 10

# ---- Prepare data ----
def encode(s):
    return [char2idx[c] for c in s]

data = encode(text)

inputs, targets = [], []
for i in range(len(data) - seq_len):
    inputs.append(data[i:i+seq_len])
    targets.append(data[i+1:i+seq_len+1])

inputs = torch.tensor(inputs)
targets = torch.tensor(targets)

# ---- Model ----
class CharRNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, 32)
        self.rnn = nn.RNN(32, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):
        x = self.embed(x)
        out, _ = self.rnn(x)
        out = self.fc(out)
        return out

model = CharRNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=lr)

# ---- Training ----
losses = []

for epoch in range(epochs):
    optimizer.zero_grad()

    output = model(inputs)
    loss = criterion(output.view(-1, vocab_size), targets.view(-1))

    loss.backward()
    optimizer.step()

    losses.append(loss.item())
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

#Text Generation
import torch.nn.functional as F
import random

def sample(model, start="h", length=200, temp=1.0):
    model.eval()
    chars = [start]

    for _ in range(length):
        x = torch.tensor([[char2idx[chars[-1]]]])
        out = model(x)[:, -1, :]

        probs = F.softmax(out / temp, dim=-1).detach().numpy()[0]
        idx = random.choices(range(vocab_size), weights=probs)[0]

        chars.append(idx2char[idx])

    return "".join(chars)

print(sample(model, temp=0.7))
print(sample(model, temp=1.0))
print(sample(model, temp=1.2))

#Loss curve
import matplotlib.pyplot as plt

plt.plot(losses)
plt.title("Training Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

#Question 2
import math
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# -----------------------------
# 1) Small dataset: 10 sentences
# -----------------------------
sentences = [
    "i like deep learning",
    "transformers use self attention",
    "neural networks learn features",
    "attention helps capture context",
    "rnn models process sequences",
    "embeddings represent words as vectors",
    "positional encoding adds order information",
    "multi head attention learns relations",
    "feed forward layers transform features",
    "layer norm stabilizes training"
]

# -----------------------------
# 2) Tokenize and build vocab
# -----------------------------
tokenized = [s.lower().split() for s in sentences]

special_tokens = ["<pad>"]
vocab = special_tokens + sorted({word for sent in tokenized for word in sent})
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for w, i in word2idx.items()}

max_len = max(len(sent) for sent in tokenized)

def encode_sentence(tokens, max_len):
    ids = [word2idx[w] for w in tokens]
    mask = [1] * len(ids)
    while len(ids) < max_len:
        ids.append(word2idx["<pad>"])
        mask.append(0)
    return ids, mask

encoded = [encode_sentence(sent, max_len) for sent in tokenized]
input_ids = torch.tensor([x[0] for x in encoded], dtype=torch.long)   # [B, T]
attention_mask = torch.tensor([x[1] for x in encoded], dtype=torch.bool)  # [B, T]

# -----------------------------
# 3) Sinusoidal positional encoding
# -----------------------------
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=100):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float32).unsqueeze(1)
        div_term = torch.exp(
            torch.arange(0, d_model, 2, dtype=torch.float32) * (-math.log(10000.0) / d_model)
        )
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer("pe", pe.unsqueeze(0))  # [1, T, D]

    def forward(self, x):
        seq_len = x.size(1)
        return x + self.pe[:, :seq_len, :]

# -----------------------------
# 4) Transformer encoder blocks
# -----------------------------
class MultiHeadSelfAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()
        assert d_model % num_heads == 0
        self.d_model = d_model
        self.num_heads = num_heads
        self.head_dim = d_model // num_heads

        self.W_q = nn.Linear(d_model, d_model)
        self.W_k = nn.Linear(d_model, d_model)
        self.W_v = nn.Linear(d_model, d_model)
        self.W_o = nn.Linear(d_model, d_model)

    def forward(self, x, mask=None):
        # x: [B, T, D]
        B, T, D = x.shape

        Q = self.W_q(x).view(B, T, self.num_heads, self.head_dim).transpose(1, 2)  # [B,H,T,Hd]
        K = self.W_k(x).view(B, T, self.num_heads, self.head_dim).transpose(1, 2)
        V = self.W_v(x).view(B, T, self.num_heads, self.head_dim).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.head_dim)  # [B,H,T,T]

        if mask is not None:
            # mask: [B, T] -> [B, 1, 1, T]
            attn_mask = mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(~attn_mask, float("-inf"))

        attn_weights = torch.softmax(scores, dim=-1)  # [B,H,T,T]
        context = torch.matmul(attn_weights, V)       # [B,H,T,Hd]

        context = context.transpose(1, 2).contiguous().view(B, T, D)  # [B,T,D]
        output = self.W_o(context)  # [B,T,D]
        return output, attn_weights

class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Linear(d_ff, d_model)
        )

    def forward(self, x):
        return self.net(x)

class EncoderBlock(nn.Module):
    def __init__(self, d_model, num_heads, d_ff):
        super().__init__()
        self.mha = MultiHeadSelfAttention(d_model, num_heads)
        self.norm1 = nn.LayerNorm(d_model)
        self.ffn = FeedForward(d_model, d_ff)
        self.norm2 = nn.LayerNorm(d_model)

    def forward(self, x, mask=None):
        attn_out, attn_weights = self.mha(x, mask)
        x = self.norm1(x + attn_out)   # Add & Norm
        ffn_out = self.ffn(x)
        x = self.norm2(x + ffn_out)    # Add & Norm
        return x, attn_weights

class MiniTransformerEncoder(nn.Module):
    def __init__(self, vocab_size, d_model=32, num_heads=4, d_ff=64, max_len=100):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoding = PositionalEncoding(d_model, max_len)
        self.encoder = EncoderBlock(d_model, num_heads, d_ff)

    def forward(self, input_ids, mask=None):
        x = self.embedding(input_ids)      # token embeddings
        x = self.pos_encoding(x)           # add positional encoding
        x, attn_weights = self.encoder(x, mask)
        return x, attn_weights

# -----------------------------
# 5) Run model
# -----------------------------
torch.manual_seed(42)

model = MiniTransformerEncoder(
    vocab_size=len(vocab),
    d_model=32,
    num_heads=4,
    d_ff=64,
    max_len=max_len
)

contextual_embeddings, attn_weights = model(input_ids, attention_mask)

# -----------------------------
# 6) Show input tokens
# -----------------------------
print("Input tokens:\n")
for i, sent in enumerate(tokenized):
    print(f"Sentence {i+1}: {sent}")

# -----------------------------
# 7) Show final contextual embeddings
# -----------------------------
print("\nFinal contextual embeddings shape:", contextual_embeddings.shape)
print("\nContextual embeddings for Sentence 1:")
print(contextual_embeddings[0])   # [T, D]

# -----------------------------
# 8) Attention heatmap
# -----------------------------
# Show heatmap for sentence 1, head 1
sent_idx = 0
head_idx = 0

valid_len = attention_mask[sent_idx].sum().item()
tokens = tokenized[sent_idx]

heatmap = attn_weights[sent_idx, head_idx, :valid_len, :valid_len].detach().numpy()

plt.figure(figsize=(6, 5))
plt.imshow(heatmap, cmap="viridis")
plt.colorbar()
plt.xticks(range(valid_len), tokens, rotation=45)
plt.yticks(range(valid_len), tokens)
plt.title("Attention Heatmap (Sentence 1, Head 1)")
plt.xlabel("Key tokens")
plt.ylabel("Query tokens")
plt.tight_layout()
plt.show()

#Question 3
import torch
import math

torch.manual_seed(42)

def scaled_dot_product_attention(Q, K, V):
    d_k = Q.size(-1)

    # Step 1: compute scores
    scores = torch.matmul(Q, K.transpose(-2, -1))

    # Step 2: scale
    scaled_scores = scores / math.sqrt(d_k)

    # Step 3: softmax
    weights = torch.softmax(scaled_scores, dim=-1)

    # Step 4: weighted sum
    output = torch.matmul(weights, V)

    return weights, output


# ---- Test ----
Q = torch.randn(2, 4)
K = torch.randn(2, 4)
V = torch.randn(2, 4)

weights, output = scaled_dot_product_attention(Q, K, V)

print("Attention Weights:\n", weights)
print("\nOutput:\n", output)